include ../MakeFile.in

F90FILES = write_out.f90

FC = gfortran
OFILES = $(F90FILES:.f90=.o)
MODFILES = $(F90FILES:.f90=.mod)
EXEFILES = $(F90FILES:.f90=)

make:
	$(FC) -J$(MODDIR) -c $(F90FILES) -o $(OBJDIR)/$(OFILES)

